# action.yml
name: 'Discord Webhook Action'
description: 'Use discord webhooks to send basic messages'
branding:
  icon: message-square
  color: purple
inputs:
  webhook-url:
    description: 'Webhook URL from discord. See: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks for details'
    required: true
  content:  # id of input
    description: 'Message that is send via the webhook.'
    required: true
  username: 
    description: 'The username that should appear to send the message. Note: username will have the "bot" badge next to their name.'
    required: false
  avatar-url:
    description: 'URL for the avatar that should appear with the message.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.webhook-url }}
    - ${{ inputs.content }}
    - ${{ inputs.username }}
    - ${{ inputs.avatar-url }}
