# action.yml
name: 'Discord Webhook Action'
description: 'Send custom messages or upload files to discord webhooks with simple action inputs.'
branding:
  icon: message-square
  color: purple
inputs:
  URL:
    description: 'Webhook URL from discord. See: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks for details'
    required: true
  SUMMARY:
    description: 'Summary of errors .. JSON format'
    required: true
  FILES:
    description: 'trace file'
    required: true
  USERNAME:
    description: 'Username of the bot'
    required: true
  DESCRIPTION:
    description: 'message'
    required: true
  COLOR:
    description: 'color of the embed'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
